export const ADD_APARTMENT = 'ADD_APARTMENT'
export const ADD_APARTMENT_OK = 'ADD_APARTMENT_OK'
export const ADD_APARTMENT_ERROR = 'ADD_APARTMENT_ERROR'

export const BEGIN_APARTMENTS_DOWNLOAD = 'BEGIN_APARTMENTS_DOWNLOAD'
export const APARTMENTS_DOWNLOAD_OK = 'APARTMENTS_DOWNLOAD_OK'
export const APARTMENTS_DOWNLOAD_ERROR = 'APARTMENTS_DOWNLOAD_ERROR'

export const RETRIEVE_APARTMENT_DELETE = 'RETRIEVE_APARTMENT_DELETE'
export const APARTMENT_DELETED_OK = 'APARTMENT_DELETED_OK'
export const APARTMENT_DELETED_ERROR = 'APARTMENT_DELETED_ERROR'

export const RETRIEVE_APARTMENT_EDIT= 'RETRIEVE_APARTMENT_EDITED'
export const BEGIN_EDIT_APARTMENT = 'BEGIN_EDIT_APARTMENT'
export const APARTMENT_EDITED_OK = 'APARTMENT_EDITED_OK'
export const APARTMENT_EDITED_ERROR = 'APARTMENT_EDITED_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'