export const ADD_APARTMENTDOOR = 'ADD_APARTMENTDOOR'
export const ADD_APARTMENTDOOR_OK = 'ADD_APARTMENTDOOR_OK'
export const ADD_APARTMENTDOOR_ERROR = 'ADD_APARTMENTDOOR_ERROR'

export const BEGIN_APARTMENTDOORS_DOWNLOAD = 'BEGIN_APARTMENTDOORS_DOWNLOAD'
export const APARTMENTDOORS_DOWNLOAD_OK = 'APARTMENTDOORS_DOWNLOAD_OK'
export const APARTMENTDOORS_DOWNLOAD_ERROR = 'APARTMENTDOORS_DOWNLOAD_ERROR'

export const RETRIEVE_APARTMENTDOOR_DELETE = 'RETRIEVE_APARTMENTDOOR_DELETE'
export const APARTMENTDOOR_DELETED_OK = 'APARTMENTDOOR_DELETED_OK'
export const APARTMENTDOOR_DELETED_ERROR = 'APARTMENTDOOR_DELETED_ERROR'

export const RETRIEVE_APARTMENTDOOR_EDIT= 'RETRIEVE_APARTMENTDOOR_EDITED'
export const BEGIN_EDIT_APARTMENTDOOR = 'BEGIN_EDIT_APARTMENTDOOR'
export const APARTMENTDOOR_EDITED_OK = 'APARTMENTDOOR_EDITED_OK'
export const APARTMENTDOOR_EDITED_ERROR = 'APARTMENTDOOR_EDITED_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'