export const ADD_RESIDENT = 'ADD_RESIDENT'
export const ADD_RESIDENT_OK = 'ADD_RESIDENT_OK'
export const ADD_RESIDENT_ERROR = 'ADD_RESIDENT_ERROR'

export const BEGIN_RESIDENTS_DOWNLOAD = 'BEGIN_RESIDENTS_DOWNLOAD'
export const RESIDENTS_DOWNLOAD_OK = 'RESIDENTS_DOWNLOAD_OK'
export const RESIDENTS_DOWNLOAD_ERROR = 'RESIDENTS_DOWNLOAD_ERROR'

export const RETRIEVE_RESIDENT_DELETE = 'RETRIEVE_RESIDENT_DELETE'
export const RESIDENT_DELETED_OK = 'RESIDENT_DELETED_OK'
export const RESIDENT_DELETED_ERROR = 'RESIDENT_DELETED_ERROR'

export const RETRIEVE_RESIDENT_EDIT= 'RETRIEVE_RESIDENT_EDITED'
export const BEGIN_EDIT_RESIDENT = 'BEGIN_EDIT_RESIDENT'
export const RESIDENT_EDITED_OK = 'RESIDENT_EDITED_OK'
export const RESIDENT_EDITED_ERROR = 'RESIDENT_EDITED_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'